package com.universidad.triage_back.enums;
public enum RequestType {
    REGISTRO_ASIGNATURA, HOMOLOGACION, CANCELACION_ASIGNATURA,
    SOLICITUD_CUPO, CONSULTA_ACADEMICA, CORRECCION_NOTA, CERTIFICADO_CONSTANCIA
}
